atomosDev/Models/Cliente.cs
using System;
using System.Collections.Generic;

namespace atomosDev.Models
 /*
 "id": 6,
        "nome": "Vanessa Gomes",
        "email": "vanessa@itau.com",
        "telefone": "(11) 98709-4781",
        "cpf": "368.478.789-13",
        "contas": [
            */

{
    public class Cliente
    {
        public string nome {get; set;}
        public string email {get; set;}
        public string telefone {get; set;}
        public string cpf {get; set;}

        public List<Conta> contas {get;set;}

    }
}

atomosDev/Models/Conta.cs
using System;
using System.Collections.Generic;

namespace atomosDev.Models
{
    /*
    "id": 5,
    "agencia": 777,
    "conta": "741258",
    "saldo": 9.0,
    "titular_da_conta": {
        "id": 6,
        "nome": "Vanessa Gomes",
        "email": "vanessa@itau.com",
        "telefone": "(11) 98709-4781",
        "cpf": "368.478.789-13",
        "contas": [
            */

    public class Conta
    {
        public int id {get;set;}
        public int tipo {get;set;}
        public int agencia {get;set;}
        public string conta {get;set;}
        public double saldo {get;set;}   
        public virtual Cliente titular_da_conta {get;set;}
    }
}

atomosDev/Models/ErrorViewModel.cs
using System;

namespace atomosDev.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

atomosDev/Controllers/ContaController.cs
using System;
using System.Net.Http;
using System.Collections;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using atomosDev.Models;
using System.Text.Json;
using System.Collections.Generic;

namespace atomosDev.Controllers
{
    public class ContaController : Controller
    {
        public async Task<IActionResult> AllContas()
        {
            // Definir meu cliente HTTP
            HttpClient clienteHTTP = new HttpClient();
            // Ler os dados da minha API e guardar em uma string
            string result = await clienteHTTP.GetStringAsync("http://localhost:8080/cliente/all");
            // Converter de JSON para uma lista do meu modelo/Objeto
            List<Cliente> clientes = JsonSerializer.Deserialize<List<Cliente>>(result);
            // Retorno para minha VIEW os resultados obtidos, a lista de contas.
            return View(clientes);
        }

        // Fazer o get pelo ID Conta
        [HttpGet]
        public IActionResult GetContaPorID()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GetContaPorID(int id)
        {
        HttpClient clienteHTTP = new HttpClient();

            // Guardar o resultado do JSON em uma string
            string resultado = await clienteHTTP.GetStringAsync($"http://localhost:8080/conta/id/{id}");

            Conta contas = JsonSerializer.Deserialize<Conta>(resultado);

            return View(contas);
        }
    }
}

atomosDev/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using atomosDev.Models;

namespace atomosDev.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

atomosDev/Views/Conta/AllContas.cshtml
@model List<Cliente>
@using atomosDev.Models

<h3 class="display-5">Consulte as contas</h3>
<hr>
@foreach (Cliente clientes in Model)
{
    <h5 class="display-5">Titular da Conta: @clientes.nome</h5>
    <table class="table table-striped table-hover">
        <thead>
            <th scope="col" class="th-id">Id</th>
            <th scope="col" class="th-tipo">Tipo de Conta</th>
            <th scope="col" class="th-agencia">Agencia</th>
            <th scope="col" class="th-conta">Conta</th>
            <th scope="col" class="th-saldo">Saldo</th>
        </thead>
        <tbody>
            @foreach (Conta contas in clientes.contas)
            {
                <tr>
                    <td>@contas.id</td>
                    <td>
                        @switch(contas.tipo)
                        {
                            case 0: <text>Conta Corrente</text>; break;
                            case 1: <text>Conta Poupança</text>; break;
                            case 2: <text>Conta Investimento</text>; break;
                        }
                    </td>
                    <td>@contas.agencia</td>
                    <td>@contas.conta</td>
                    <td class="td-saldo">R$ @contas.saldo.ToString("n")</td>
                </tr>
            }
        </tbody>
    </table>
}

atomosDev/Views/Conta/GetContaPorID.cshtml
@model Conta

@using atomosDev.Models

<h3 class="display-5">Dados de uma conta</h3>
<hr>
<form>
    <label >ID da Conta</label>
    <input type="number" id="id" name="id">
    <input type="submit" value="Procurar" formmethod="POST">
</form>

@if(Model!=null)
{
    <div class="container">
        <div class="row">
            <div class="col-12">
                <label><b>Tipo de Conta: </b>
                @switch(@Model.tipo)
                {
                    case 0: <text>Conta Corrente</text>; break;
                    case 1: <text>Conta Poupança</text>; break;
                    case 2: <text>Conta Investimento</text>; break;
                }
                </label>
            </div>
            <div class="col-12">
                <label><b>Agencia: </b>@Model.agencia</label>
            </div>
            <div class="col-12">
                <label><b>Conta: </b>@Model.conta</label>
            </div>
            <div class="col-12">
                <label><b>Saldo: </b>R$ @Model.saldo.ToString("n")</label>
            </div>
            <div class="col-12">
                <label><b>Titular da Conta: </b>@Model.titular_da_conta.nome</label>
            </div>
            <div class="col-12">
                <label><b>CPF: </b>@Model.titular_da_conta.cpf</label>
            </div>
            <div class="col-12">
                <label><b>Telefone: </b>@Model.titular_da_conta.telefone</label>
            </div>
            <div class="col-12">
                <label><b>Email: </b>@Model.titular_da_conta.email</label>
            </div>
        </div>
    </div>
}

atomosDev/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h5 class="display-5">Seja bem vindo!</h5>
    <h1 class="display-4">Projeto Final Formação Tech Itaú</h1>
    <br>
    <a href="https://github.com/Suzyguebata/api-spring-boot-itautech">Gerenciamento de clientes e contas bancárias da instituição para consulta, utilizando API Spring Boot e .Net</a>
</div>

atomosDev/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - atomosDev</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <img src="https://uploaddeimagens.com.br/images/003/461/649/original/WEBG_PNG.png?1633142919" alt="" srcset="" width = "200px" height="auto">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Sobre</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Conta" asp-action="AllContas">Todas as Contas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Conta" asp-action="GetContaPorID">Consultar Contas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - atomosDev - <a asp-area="" asp-controller="Home" asp-action="Privacy">Sobre</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>